p_manager/urls.py
from django.urls import path
from .import views


app_name = 'p_manager'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.auth_login, name='login'),
    path('logout/', views.auth_logout, name='logout'),
    path('index/', views.index, name='index'),
    path('change_user/', views.UserUpdateView.as_view(), name='update_user'),
    path('update/<pk>', views.PasswordUpdateView.as_view(), name="update"),
    path('create/', views.create_new_password, name='create_pass'),
    path('add/', views.add_pass, name='add_pass')
]

p_manager/models.py
from django.db import models
from django.contrib.auth.models import User


class Password(models.Model):
    pw_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    pass_id = models.CharField('ID', max_length=26, primary_key=True)
    pw = models.CharField('パスワード', max_length=300)
    purpose = models.TextField('使用場所', max_length=100, blank=True)
    description = models.TextField('補足', max_length=500, blank=True)

    def __str__(self):
        return self.pass_id










p_manager/forms.py
from django import forms

from .models import Password
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PasswordForm(forms.ModelForm):

    class Meta:
        
        model = Password
        fields = ("pw", "purpose", "description")


class SignupForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

p_manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import UpdateView
from django.utils.decorators import method_decorator

import ulid

from . import manager
from .models import Password
from .forms import PasswordForm, SignupForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            request.session['master_pass'] = request.POST['username'] + request.POST['password1']
            return redirect('p_manager:index')
    else:
        form = SignupForm()
    return render(request, 'p_manager/signup.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class PasswordUpdateView(UpdateView):
    model = Password
    form_class = PasswordForm
    template_name = "p_manager/update.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(pw_user=self.request.user)

    def get_context_data(self, **kwargs):
        master_pass = self.request.session['master_pass']
        operation = manager.DBOperation(master_pass)

        context_data = super().get_context_data()
        if self.request.method == 'GET':
            form = context_data['form']
            e_pass = form['pw'].value()
            d_pass = operation.decrypt_pass(e_pass)
            new_form = {'pw': d_pass,
                        'purpose': form['purpose'].value(),
                        'description': form['description'].value()}
            context_data['form'] = PasswordForm(new_form)
        return context_data

    def form_valid(self, form):
        post = form.save(commit=False)

        pw_dict = self.request.session['pw_dict']
        pk = self.kwargs['pk']
        for num, pw in enumerate(pw_dict):
            if pw['id'] == pk:
                pw_dict[num] = {'id': pk,
                                'password': post.pw,
                                'purpose': post.purpose,
                                'description': post.description}
        self.request.session['pw_dict'] = pw_dict

        post.pw_user = self.request.user
        master_pass = self.request.session['master_pass']
        operation = manager.DBOperation(master_pass)
        post.pw = operation.encrypt_pass(post.pw)
        post.save()

        return redirect('p_manager:index')


@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    fields = ('username', 'email',)
    template_name = 'p_manager/change_user.html'
    success_url = 'p_manager:change_user'

    def get_object(self):
        return self.request.user


@login_required
def index(request):
    try:
        pw_dict = request.session['pw_dict']
    except KeyError:
        pw_dict = None

    if request.method == 'POST':
        try:
            pw_id = request.POST["del_pw"]
        except KeyError:
            return redirect('p_manager:index')

        delete_pw = Password.objects.get(pass_id=pw_id)
        delete_pw.delete()

        for num, pw in enumerate(pw_dict):
            print(pw['id'])
            if pw['id'] == pw_id:
                pw_dict.pop(num)
                print('Delete Success')
        request.session['pw_dict'] = pw_dict

    master_pass = request.session['master_pass']
    operation = manager.DBOperation(master_pass)
    pw_model = Password.objects.filter(pw_user=request.user)

    if pw_dict is None:
        pw_dict = [{'id': i.pass_id,
                    'password': operation.decrypt_pass(i.pw),
                    'purpose': i.purpose,
                    'description': i.description
                    } for i in pw_model]
        request.session['pw_dict'] = pw_dict
        print(request.session['pw_dict'])

    return render(request, 'p_manager/index.html', {'pw_dict': pw_dict})


def auth_login(request):
    if request.user.is_authenticated:
        return redirect('p_manager:index')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            request.session['master_pass'] = username + password
            return redirect('p_manager:index')
        else:
            error_message = 'Username or password is invalid.'
            return render(request, 'p_manager/login.html', {'error_message': error_message})
    else:
        return render(request, 'p_manager/login.html')


@login_required
def auth_logout(request):
    logout(request)
    request.session.flush()
    return redirect('p_manager:login')


@login_required
def create_new_password(request):
    if request.method == "POST":
        pass_len = int(request.POST['len'])
        try:
            uppercase = int(request.POST['uppercase'])
        except KeyError:
            uppercase = 0
        try:
            symbol = int(request.POST['symbol'])
        except KeyError:
            symbol = 0
        password = manager.create_pass(pass_len=pass_len,
                                       uppercase=uppercase,
                                       symbol=symbol)
        # print(password)

        return render(request, 'p_manager/add.html', {'password': password})
    else:
        return render(request, 'p_manager/create_pass.html')


@login_required
def add_pass(request):
    try:
        pass_id = ulid.new()
        master_pass = request.session['master_pass']
        operation = manager.DBOperation(master_pass)
        e_pass = operation.encrypt_pass(request.POST['password'])
        pw_user = request.user
        Password.objects.create(pw_user=pw_user,
                                pass_id=pass_id,
                                pw=e_pass,
                                purpose=request.POST['purpose'],
                                description=request.POST['description'])

        try:
            pw_dict = request.session['pw_dict']
        except KeyError:
            return redirect('p_manager:index')

        pw_dict.append({'id': pass_id.str,
                        'password': request.POST['password'],
                        'purpose': request.POST['purpose'],
                       'description': request.POST['description']
                        })
        request.session['pw_dict'] = pw_dict
        print(pw_dict)
        return redirect('p_manager:index')

    except KeyError:
        return render(request, 'p_manager/add.html')


p_manager/templates/p_manager/add.html
{% extends 'p_manager/base.html' %}
{% block title %}Add Password {% endblock title %}
{% block body %}
<div id="wrapper">
    <div id="page-wrapper" style="min-height:  534px;">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Add New Password
                    </div>
                    <div class="panel-body">
                        <form method="post" action="{% url 'p_manager:add_pass' %}" role="form">
                        {% csrf_token %}
                            <div class="form-group">
                                <label>Password</label>
                                 <input type="text" class="form-control" value="{% if password %}{{password}}{% endif %}" name="password">
                            </div>
                            <div class="form-group">
                                <label>Purpose</label>
                                <input class="form-control" name="purpose" placeholder="No text">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control" name="description" rows="3"> </textarea>
                            </div>
                            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Add Password">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

p_manager/templates/p_manager/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
{% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Password Index{% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'p_manager/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'p_manager/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{% static 'p_manager/vendor/datatables-plugins/dataTables.bootstrap.css' %}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{% static 'p_manager/vendor/datatables-responsive/dataTables.responsive.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'p_manager/dist/css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'p_manager/vendor/datatables/css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>
    <!-- Custom Fonts -->
    <link href="{% static 'p_manager/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
    <![endif]-->
    {% block stylesheet %}
    {% endblock stylesheet %}
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'p_manager:index' %}">Django Boards</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="#">My account</a>
                  <a class="dropdown-item" href="{% url 'p_manager:update_user' %}">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'p_manager:logout' %}">Log out</a>
                </div>
              </li>
            </ul>
          {% else %}
            <form class="form-inline ml-auto">
              <a href="{% url 'p_manager:login' %}" class="btn btn-outline-secondary">Log in</a>
              <a href="{% url 'p_manager:signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- jQuery -->
    <script src="{% static 'p_manager/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'p_manager/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Popper JavaScript -->
    <script src="{% static 'p_manager/dist/js/popper.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'p_manager/vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- DataTables JavaScript -->
    <script src="{% static 'p_manager/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'p_manager/vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'p_manager/vendor/datatables-responsive/dataTables.responsive.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'p_manager/dist/js/sb-admin-2.js' %}"></script>

    {% block body %}
    {% endblock body %}
</body>
</html>

p_manager/templates/p_manager/change_user.html
{% extends 'p_manager/base.html' %}
{% block title %}
Change Account
{% endblock %}
{% block body %}
    <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="post" novalidate>
            {%  csrf_token %}
            {%  include 'p_manager/form.html' %}
            <button type="submit" class="btn btn-success">Save changes</button>
        </form>
    </div>
    </div>
{% endblock body %}

p_manager/templates/p_manager/create_pass.html
{% extends 'p_manager/base.html' %}
{% block title %}Create New Password {% endblock title %}
{% block body %}
    <div id="wrapper">
        <div id="page-wrapper" style="min-height: 534px;">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Select options for new password
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <form role="form" action="{% url 'p_manager:create_pass' %}" method="post" name="p_form" onsubmit="return checkPassword()">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label>Password Length</label>
                                        <input class="form-control" name="len" value="16" size="20">
                                    </div>
                                    <div class="form-group">
                                        <label>Password Options </label>
                                        <div class="checkbox">
                                           <label>
                                               <input type="checkbox" value="1" name="uppercase" checked="checked">Enable uppercase (ex:ABC...)
                                           </label>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" value="1" name="symbol" checked="checked">Enable symbols (ex:!/&...)
                                            </label>
                                        </div>
                                    </div>
                                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Create Password">
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
    function checkPassword(){
        let pass_len = document.p_form.len.value;
        pass_len = Number(pass_len);
        if (pass_len <= 4){
            alert('Password Length is too short.');
            return false
        } else if(pass_len >100){
            alert('Password Length is too long');
            return false
        }
    }
</script>
{% endblock body %}

p_manager/templates/p_manager/form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text|safe }}
            </small>
        {% endif %}
    </div>
{% endfor %}

p_manager/templates/p_manager/index.html
{% extends 'p_manager/base.html' %}
{% block body %}
<div id="wrapper">
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Password List</h1>
            </div>
            <div class="col-lg-12">
                <div class="panel-body">
                    <table width="100%" id="dataTables-example" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Password</th>
                                <th>Purpose</th>
                                <th>Description</th>
                                <th>Operation</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for pass_row in pw_dict %}
                            <tr name="pw_row{{forloop.counter}}">
                                <th class="col-lg-2" id="pw_id{{ forloop.counter }}">{{ pass_row.id }}</th>
                                <th class="col-lg-4" id="pw{{ forloop.counter }}">
                                    <span id="pw_sp{{ forloop.counter}}">{{ pass_row.password }}</span>
                                    <button class="btn btn-xs" data-clipboard-target="#pw_sp{{ forloop.counter }}" id="clip{{ forloop.counter }}">
                                        <span class="fa fa-copy"></span>
                                    </button>
                                </th>
                                <th class="col-lg-2" id="purpose{{forloop.counter}}">{{ pass_row.purpose }}</th>
                                <th class="col-lg-3" id="desc{{forloop.counter}}">{{ pass_row.description }}</th>
                                <th class="col-lg-1">
                                <button type="button" class="btn-success btn-circle" onclick="location.href='{% url "p_manager:update" pass_row.id %}'">
                                    <i class="fa fa-wrench"></i>
                                </button>
                                <form style="display: inline" onsubmit="return delPassword({{forloop.counter}})" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="del_pw" value="{{ pass_row.id }}">
                                    <button type="submit" class="btn-danger btn-circle">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </form>
                                </th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <button class="btn btn-primary btn-lg btn-block" onclick="linkCreate()">
                Create New Password
            </button>
        </div>
        <div class="row">
            <button class="btn btn-success btn-lg btn-block" onclick="location.href='{% url "p_manager:add_pass" %}'">
                Add New Password
            </button>
        </div>
    </div>
</div>
{% load staticfiles %}
<script src="{% static 'p_manager/dist/js/clipboard.min.js' %}"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        jQuery(function ($) {
            $("#dataTables-example").DataTable({
                // enable scroll bar
                scrollX: true,

                // disable Password Id col
                columnDefs:[
                    { targets: 0, visible: false }
            ]});
        });
        function linkCreate() {
            location.href="{% url 'p_manager:create_pass' %}"
        }
        function delPassword(num) {
            let pw_num = 'pw_sp' + String(num);
            let pw_id = document.getElementById(pw_num);
            let password = pw_id.textContent;
            let result = window.confirm('Are You sure to delete '+password+' ?');
            return result
        }
    {% for i in pw_dict %}
        $(function () {
          let clipboard = new ClipboardJS('#clip{{ forloop.counter }}');
          clipboard.on('success', function (e) {

              e.clearSelection();
          })
        });
    {% endfor %}
    </script>


{% endblock body %}

p_manager/templates/p_manager/login.html
{% extends 'p_manager/base.html' %}
{% block title %}Login page {% endblock title %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post">
                        {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="username" name="username" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                {% if error_message %}
                                <p class="text-danger">
                                    {{error_message}}
                                </p>
                                {% endif %}
                                <!-- Change this to a button or input when using this as a form -->
                                <input type="submit" class="btn btn-lg btn-success btn-block" value="Login">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

p_manager/templates/p_manager/signup.html
{% extends 'p_manager/base.html' %}
{% block title %}Sign Up Form {% endblock title %}
{% block body %}
  <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Create New Account</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" action="{% url 'p_manager:signup' %}" method="post">
                        {% csrf_token %}
                                <!--<div class="form-group">-->
                                    <!--<label>Username</label>-->
                                    <!--<input class="form-control" placeholder="username" name="username">-->
                                <!--</div>-->
                                <!--<div class="form-group">-->
                                    <!--<label>Password</label>-->
                                    <!--<input class="form-control" placeholder="Password" name="password1" type="password">-->
                                <!--</div>-->
                                <!--<div class="form-group">-->
                                    <!--<label>Confirm Password</label>-->
                                    <!--<input class="form-control" placeholder="confirm password" name="password2" type="password">-->
                                <!--</div>-->
                            {% include 'p_manager/form.html' %}
                            <input type="submit" class="btn btn-lg btn-success btn-block" value="Register">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

p_manager/templates/p_manager/update.html
{% extends 'p_manager/base.html' %}

{% block title %} Password Update {% endblock title %}
{% block body %}
 <div id="wrapper">
    <div id="page-wrapper" style="min-height:  534px;">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Add New Password
                    </div>
                    <div class="panel-body">
                        <form method="post" class="mb-4" novalidate>
                        {% csrf_token %}
                        {% include 'p_manager/form.html' %}
                            <button type="submit" class="btn btn-success">Save changes</button>
                            <a href="{% url 'p_manager:index' %}" class="btn btn-primary" role="button">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body%}